### PR TITLE
Version 3 iOS 15 & macOS 12

### PR DESCRIPTION
**Pull request by AndreaMiotto**
In this version I refactored a lot the project.

Now the user will interact with the PartialSheet just with 2 modifiers:
- One to attach the Partial Sheet to the view hierarchy
- One to display it trough a bindable bool (Like any view in SwiftUI)

More Done:
- Added the Material support to have the blurred background
- Reviewed the documentations
- Reviewed the examples
- FullScreen compatible
- Adjusted bottom insets

Todo:

- Disable automatic cose of the sheet
- Check iPad 
- Check Mac OS 12
- Check the opened issues to see if it's the case to fix something
- Add a full screen example
- Add a sheet example
- Fix bottom insets in case partial sheet is presented from a sheet

## Warning

Version 3 will support only iOS 15+ and macOS 12+.
Anyone that needs to support previous versions of OS will need to use the Version 2

### CODE REVIEW

**Comment by styrken** [comment]
Cool. I have not looked at it yet but I will test it out and come back :)

**Comment by styrken** [comment]
I have checked out the code and tested it and it works really well.  There is however still one issue that we also had in version 2. It relates to Pickers (of wheel type). But i guess it could relate to any subview that has some kind of drag gesture. At some point we had an issue where it was not possible to tap inside a textfield or switch a switch. This seems to be fixed however.

**PickerExample.swift**

If you change the PickerView Example to the following content view, you can no longer drag the wheel. I am not sure how to fix this, as it has to do with how the drag-gesture takes over the drag gesture inside the wheel picker.

```
struct PickerSheetView: View {
    var strengths = ["Mild", "Medium", "Mature"]
    @State private var selectedStrength = 0

    var body: some View {
        VStack {
            VStack {
                Text("Settings Panel").font(.headline)
                Picker(selection: $selectedStrength, label: EmptyView()) {
                    ForEach(0 ..< strengths.count) {
                        Text(self.strengths[$0])
                    }
                }.pickerStyle(.wheel)
            }
            .padding()
            .frame(height: 250)
        }
    }
}
```

**Comment by grangej** [comment]
Is there anything we can do to help speed this PR along? Happy to contribute

**Comment by AndreaMiotto** [comment]
Hey guys, sorry for the delay, I did some major changes to this PR, I still have few things more and then it is ready, feel free to try it out

**Comment by egistli** [comment]
@styrken I have faced the same picker won't scroll issue like you did and sadly found out this fix is for version 3 and iOS 15 only while I have to support lower iOS versions.

However for the people who also in the same shoes, try adding `.onTapGesture {}` to the containing view of the picker view. (For exmaple, the `VStack` contains the picker view in the example provided by @styrken). 
I think the onTapGesture somehow delays the trigerring of drag gesture registered by PartialSheet and make PickerView scrollable again.

ref: https://stackoverflow.com/questions/57700396/adding-a-drag-gesture-in-swiftui-to-a-view-inside-a-scrollview-blocks-the-scroll

**Pull request merged**
