### PR TITLE
Add public init to style struct

### PR DESCRIPTION
**Pull request by voltec**
added public init method

### CODE REVIEW

**Comment by styrken** [comment]
What issue does this PR solve ?

**Comment by voltec** [comment]
> What issue does this PR solve ?
I can't use the init method in swift package dependencies because it's not public.

**Comment by styrken** [comment]
Okay, I though structs created the inits automatically but that might not be case when imported as a package?

**Comment by voltec** [comment]
> Okay, I though structs created the inits automatically but that might not be case when imported as a package?
I only see public methods and variables:
`public struct PartialSheetStyle {

    /// Background enum
    public enum PartialSheetBackground {

        case solid(Color)

        case blur(UIBlurEffect.Style)
    }
}

extension PartialSheetStyle {

    /** A default Style for the PartialSheet with system colors.
    
         - background: .solid(Color(UIColor.tertiarySystemBackground))
         - handlerBarColor: Color(UIColor.systemGray2)
         - enableCover: true
         - coverColor: Color.black.opacity(0.4)
         - blurEffectStyle: nil
         */
    public static func defaultStyle() -> PartialSheet.PartialSheetStyle
}`

**Comment by styrken** [comment]
Yes but the compiler creates the init for you?

https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID213

(See Memberwise Initializers for Structure Types)

**Comment by jtrespalacios** [comment]
I'm also running into this issue when using this package, not able to init `PartialSheetStyle` from application code

**Comment by styrken** [comment]
Okay, i will have a look

**Comment by 1337domz** [comment]
Unfortuantly the default for a Struct memberwise initializer is 'internal':

https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html

> The default memberwise initializer for a structure type is considered private if any of the structure’s stored properties are private. Likewise, if any of the structure’s stored properties are file private, the initializer is file private. Otherwise, the initializer has an access level of internal.
>
> As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition.

**Comment by styrken** [comment]
Thanks for the clarification. I will be merging the PR shortly.

**Review by styrken — APPROVED** [review]

**Pull request merged**
